In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re

In [2]:
fullData = pd.read_csv('FIFA_data.csv', index_col=0)
droppable_cols = ['Real Face', 'Joined', 'Contract Valid Until','Photo', 'Flag', 'Club Logo', 'Special', 'Body Type']
usefulData = fullData.drop(columns=droppable_cols, errors='ignore')
#usefulData.head()

In [3]:
usefulData['TotalPassing'] = (usefulData['ShortPassing'] + usefulData['LongPassing'])/2
usefulData['GrowthPotential'] = usefulData['Potential'] - usefulData['Overall']

In [4]:
def convert(value):
    #value = row.Value
    lastChar = value[-1]
    try:
        if lastChar == 'K':
            value = str(float(value[0:-1])*100)
        elif lastChar == 'M':
            value = str(float(value[0:-1])*100000)
    except: 
        if lastChar == 'K':
            value = str(float(value[0])*100)
        elif lastChar == 'M':
            value = str(float(value[0])*100000)
    return value
# end of def convert

In [5]:
def symbolFix(value):
    'removes the symbols from the string'
    value = value.replace('€','')
    return value

In [6]:
def convert_v2(value):
    'hopefully a better version of convert'
    value = symbolFix(value)
    
    lastChar = value[-1]
    if lastChar == 'K':
        factor = 1000
    elif lastChar == 'M':
        factor = 1000000
    else:
        return 0
        #print('OOOPS -', value)
        
    try:
        num = float(value[:-1])
    except:
        num = value[:-1]
        print(value)
        
    return num*factor
    
# end of def convert_v2

In [7]:
usefulData.Value = usefulData.Value.apply(convert_v2)

In [8]:
#ValueSeries_String = usefulData.Value.str.replace('€','')
#ValueSeries_String = ValueSeries_String.str.replace('.','')
#usefulData.Value = ValueSeries_String

In [9]:
#usefulData.Value = usefulData.Value.apply(convert)

In [10]:
#usefulData['Value'] = usefulData.Value.astype(float)

In [11]:
#RCSeries_String = usefulData['Release Clause'].str.replace('€','')
#RCSeries_String = RCSeries_String.str.replace('.','')
#usefulData['Release Clause'] = RCSeries_String

In [12]:
usefulData.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,TotalPassing,GrowthPotential
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500000.0,€565K,Left,...,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M,88.5,0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000000.0,€405K,Right,...,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M,79.0,0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500000.0,€290K,Right,...,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M,81.0,1
3,193080,De Gea,27,Spain,91,93,Manchester United,72000000.0,€260K,Right,...,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M,50.5,2
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000000.0,€355K,Right,...,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M,91.5,1

In [13]:
usefulData['Release Clause'] = usefulData['Release Clause'].astype(str)

In [14]:
usefulData['Release Clause'] = usefulData['Release Clause'].apply(convert_v2)

In [15]:
#usefulData['Release Clause'] = usefulData['Release Clause'].astype(float)

In [16]:
#WageSeries_String = usefulData.Wage.str.replace('€','')
#WageSeries_String = WageSeries_String.str.replace('.','')
#usefulData.Wage = WageSeries_String

In [17]:
usefulData['Wage'] = usefulData['Wage'].apply(convert_v2)

In [18]:
#usefulData['Wage'] = usefulData['Wage'].astype(float)

In [19]:
usefulData.Value.describe()

count    1.820700e+04
mean     2.410696e+06
std      5.594933e+06
min      0.000000e+00
25%      3.000000e+05
50%      6.750000e+05
75%      2.000000e+06
max      1.185000e+08
Name: Value, dtype: float64

In [20]:
ClubValues = usefulData.groupby('Club').Value.sum()

In [21]:
ClubValues.Chelsea

606815000.0

In [22]:
topPlayers = usefulData.sort_values(['Overall', 'Potential'], ascending=[False, False])

In [23]:
topPlayers[200:230]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,TotalPassing,GrowthPotential
194,197965,Pizzi,28,Portugal,83,83,SL Benfica,25500000.0,22000.0,Right,...,66.0,52.0,15.0,14.0,9.0,9.0,15.0,51000000.0,83.5,0
195,195365,K. Kampl,27,Slovenia,83,83,RB Leipzig,26500000.0,74000.0,Right,...,64.0,59.0,13.0,11.0,7.0,6.0,16.0,45100000.0,81.5,0
198,193474,I. Gueye,28,Senegal,83,83,Everton,21000000.0,125000.0,Right,...,89.0,84.0,8.0,6.0,8.0,12.0,13.0,39900000.0,76.0,0
199,192883,H. Mkhitaryan,29,Armenia,83,83,Arsenal,25500000.0,145000.0,Right,...,53.0,55.0,5.0,11.0,14.0,5.0,7.0,48500000.0,75.5,0
201,192593,D. Subašić,33,Croatia,83,83,AS Monaco,13000000.0,70000.0,Right,...,14.0,13.0,82.0,80.0,79.0,82.0,84.0,24700000.0,25.0,0
202,190547,K. Glik,30,Poland,83,83,AS Monaco,19000000.0,86000.0,Right,...,85.0,82.0,10.0,14.0,5.0,8.0,10.0,36100000.0,61.0,0
203,189712,K. Strootman,28,Netherlands,83,83,Olympique de Marseille,21000000.0,66000.0,Left,...,84.0,75.0,7.0,12.0,11.0,6.0,7.0,39900000.0,85.5,0
204,189068,B. Dost,29,Netherlands,83,83,Sporting CP,26000000.0,26000.0,Right,...,45.0,26.0,6.0,12.0,15.0,11.0,8.0,52000000.0,55.0,0
206,186627,M. Balotelli,27,Italy,83,83,OGC Nice,27500000.0,55000.0,Right,...,22.0,20.0,2.0,2.0,2.0,4.0,2.0,52300000.0,72.0,0
207,185221,Luiz Gustavo,30,Brazil,83,83,Olympique de Marseille,19000000.0,63000.0,Left,...,84.0,86.0,10.0,6.0,11.0,12.0,13.0,36100000.0,78.0,0
208,184942,Giuliano,28,Brazil,83,83,Al Nassr,26000000.0,64000.0,Right,...,43.0,38.0,16.0,11.0,13.0,9.0,8.0,44200000.0,80.5,0
209,179944,David Luiz,31,Brazil,83,83,Chelsea,17500000.0,130000.0,Right,...,83.0,82.0,11.0,12.0,10.0,7.0,14.0,32400000.0,77.0,0
211,178088,Juan Mata,30,Spain,83,83,Manchester United,24500000.0,160000.0,Left,...,31.0,21.0,9.0,10.0,14.0,5.0,8.0,45300000.0,82.0,0
212,178086,Adán,31,Spain,83,83,Atlético Madrid,15500000.0,55000.0,Left,...,14.0,18.0,81.0,84.0,78.0,84.0,83.0,31800000.0,38.5,0
213,178005,Rui Patrício,30,Portugal,83,83,Wolverhampton Wanderers,16500000.0,74000.0,Left,...,13.0,11.0,85.0,81.0,80.0,79.0,82.0,31400000.0,30.5,0
215,177610,Javi Martínez,29,Spain,83,83,FC Bayern München,20000000.0,94000.0,Right,...,86.0,86.0,5.0,12.0,9.0,11.0,8.0,33000000.0,75.5,0
216,177457,L. Bender,29,Germany,83,83,Bayer 04 Leverkusen,20000000.0,82000.0,Right,...,86.0,82.0,12.0,6.0,7.0,12.0,7.0,34000000.0,76.5,0
217,176266,Lucas Leiva,31,Brazil,83,83,Lazio,17500000.0,64000.0,Right,...,82.0,78.0,10.0,8.0,8.0,5.0,6.0,29800000.0,81.5,0
218,163705,S. Mandanda,33,France,83,83,Olympique de Marseille,13000000.0,51000.0,Right,...,15.0,13.0,86.0,81.0,70.0,79.0,84.0,24700000.0,32.5,0
219,162895,Cesc Fàbregas,31,Spain,83,83,Chelsea,22000000.0,140000.0,Right,...,59.0,58.0,6.0,10.0,8.0,15.0,15.0,40700000.0,89.5,0
220,162240,M. Dembélé,30,Belgium,83,83,Tottenham Hotspur,24000000.0,120000.0,Left,...,82.0,70.0,16.0,14.0,11.0,16.0,14.0,44400000.0,83.0,0
221,156616,F. Ribéry,35,France,83,83,FC Bayern München,11500000.0,72000.0,Right,...,25.0,26.0,15.0,6.0,9.0,7.0,10.0,19000000.0,78.5,0
222,104389,R. Jarstein,33,Norway,83,83,Hertha BSC,13000000.0,33000.0,Right,...,11.0,13.0,79.0,82.0,76.0,86.0,84.0,22100000.0,34.0,0
223,53302,D. De Rossi,34,Italy,83,83,Roma,8000000.0,80000.0,Right,...,82.0,80.0,10.0,7.0,13.0,10.0,9.0,13600000.0,80.5,0
224,24630,Pepe Reina,35,Spain,83,83,Milan,6000000.0,56000.0,Right,...,22.0,24.0,80.0,83.0,82.0,82.0,82.0,10200000.0,20.5,0
229,230621,G. Donnarumma,19,Italy,82,93,Milan,29000000.0,23000.0,Right,...,14.0,16.0,88.0,78.0,72.0,78.0,88.0,55100000.0,29.0,11
226,235243,M. de Ligt,18,Netherlands,82,91,Ajax,27000000.0,11000.0,Right,...,84.0,79.0,12.0,11.0,11.0,12.0,10.0,43200000.0,73.5,9
228,230658,Arthur,21,Brazil,82,90,FC Barcelona,32500000.0,125000.0,Right,...,76.0,70.0,6.0,13.0,13.0,11.0,12.0,73100000.0,82.5,8
236,222737,Malcom,21,Brazil,82,89,FC Barcelona,31500000.0,140000.0,Left,...,28.0,17.0,8.0,14.0,15.0,7.0,9.0,70900000.0,77.5,7
248,210413,A. Romagnoli,23,Italy,82,89,Milan,26500000.0,84000.0,Left,...,85.0,81.0,9.0,14.0,12.0,8.0,9.0,50400000.0,69.5,7

In [24]:
topPlayers['Price per Overall'] = topPlayers['Value']/topPlayers['Overall']

In [25]:
topPlayers.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,TotalPassing,GrowthPotential,Price per Overall
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500000.0,565000.0,Left,...,26.0,6.0,11.0,15.0,14.0,8.0,226500000.0,88.5,0,1.175532e+06
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000000.0,405000.0,Right,...,23.0,7.0,11.0,15.0,14.0,11.0,127100000.0,79.0,0,8.191489e+05
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500000.0,290000.0,Right,...,33.0,9.0,9.0,15.0,15.0,11.0,228100000.0,81.0,1,1.288043e+06
3,193080,De Gea,27,Spain,91,93,Manchester United,72000000.0,260000.0,Right,...,13.0,90.0,85.0,87.0,88.0,94.0,138600000.0,50.5,2,7.912088e+05
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000000.0,355000.0,Right,...,51.0,15.0,13.0,5.0,10.0,13.0,196400000.0,91.5,1,1.120879e+06

In [26]:
topPlayers = topPlayers.sort_values(['Overall', 'Price per Overall', 'Potential'], ascending=[False, True, False])

In [27]:
topPlayers.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,TotalPassing,GrowthPotential,Price per Overall
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000000.0,405000.0,Right,...,23.0,7.0,11.0,15.0,14.0,11.0,127100000.0,79.0,0,8.191489e+05
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500000.0,565000.0,Left,...,26.0,6.0,11.0,15.0,14.0,8.0,226500000.0,88.5,0,1.175532e+06
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500000.0,290000.0,Right,...,33.0,9.0,9.0,15.0,15.0,11.0,228100000.0,81.0,1,1.288043e+06
8,155862,Sergio Ramos,32,Spain,91,91,Real Madrid,51000000.0,380000.0,Right,...,91.0,11.0,8.0,9.0,7.0,11.0,104600000.0,77.5,0,5.604396e+05
6,177003,L. Modrić,32,Croatia,91,91,Real Madrid,67000000.0,420000.0,Right,...,73.0,13.0,9.0,7.0,14.0,9.0,137400000.0,90.5,0,7.362637e+05

In [28]:
usefulData.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause,TotalPassing,GrowthPotential
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500000.0,565000.0,Left,...,28.0,26.0,6.0,11.0,15.0,14.0,8.0,226500000.0,88.5,0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000000.0,405000.0,Right,...,31.0,23.0,7.0,11.0,15.0,14.0,11.0,127100000.0,79.0,0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500000.0,290000.0,Right,...,24.0,33.0,9.0,9.0,15.0,15.0,11.0,228100000.0,81.0,1
3,193080,De Gea,27,Spain,91,93,Manchester United,72000000.0,260000.0,Right,...,21.0,13.0,90.0,85.0,87.0,88.0,94.0,138600000.0,50.5,2
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000000.0,355000.0,Right,...,58.0,51.0,15.0,13.0,5.0,10.0,13.0,196400000.0,91.5,1

In [29]:
usefulData.to_csv('FIFA_data_clean')

In [30]:
usefulData.to_excel('FIFA_data_clean.xlsx')